// set of words used to make password
var words = [
    'a',
    'able',
    'about',
    'account',
    'acid',
    'across',
    'act',
    'addition',
    'adjustment',
    'advertisement',
    'after',
    'again',
    'against',
    'agreement',
    'air',
    'all',
    'almost',
    'among',
    'amount',
    'amusement',
    'and',
    'angle',
    'angry',
    'animal',
    'answer',
    'ant',
    'any',
    'apparatus',
    'apple',
    'approval',
    'arch',
    'argument',
    'arm',
    'army',
    'art',
    'as',
    'at',
    'attack',
    'attempt',
    'attention',
    'attraction',
    'authority',
    'automatic',
    'awake',
    'baby',
    'back',
    'bad',
    'bag',
    'balance',
    'ball',
    'band',
    'base',
    'basin',
    'basket',
    'bath',
    'be',
    'beautiful',
    'because',
    'bed',
    'bee',
    'before',
    'behaviour',
    'belief',
    'bell',
    'bent',
    'berry',
    'between',
    'bird',
    'birth',
    'bit',
    'bite',
    'bitter',
    'black',
    'blade',
    'blood',
    'blow',
    'blue',
    'board',
    'boat',
    'body',
    'boiling',
    'bone',
    'book',
    'boot',
    'bottle',
    'box',
    'boy',
    'brain',
    'brake',
    'branch',
    'brass',
    'bread',
    'breath',
    'brick',
    'bridge',
    'bright',
    'broken',
    'brother',
    'brown',
    'brush',
    'bucket',
    'building',
    'bulb',
    'burn',
    'burst',
    'business',
    'but',
    'butter',
    'button',
    'by',
    'cake',
    'camera',
    'canvas',
    'card',
    'care',
    'carriage',
    'cart',
    'cat',
    'cause',
    'certain',
    'chain',
    'chalk',
    'chance',
    'change',
    'cheap',
    'cheese',
    'chemical',
    'chest',
    'chief',
    'chin',
    'church',
    'circle',
    'clean',
    'clear',
    'clock',
    'cloth',
    'cloud',
    'coal',
    'coat',
    'cold',
    'collar',
    'colour',
    'comb',
    'come',
    'comfort',
    'committee',
    'common',
    'company',
    'comparison',
    'competition',
    'complete',
    'complex',
    'condition',
    'connection',
    'conscious',
    'control',
    'cook',
    'copper',
    'copy',
    'cord',
    'cork',
    'cotton',
    'cough',
    'country',
    'cover',
    'cow',
    'crack',
    'credit',
    'crime',
    'cruel',
    'crush',
    'cry',
    'cup',
    'cup',
    'current',
    'curtain',
    'curve',
    'cushion',
    'damage',
    'danger',
    'dark',
    'daughter',
    'day',
    'dead',
    'dear',
    'death',
    'debt',
    'decision',
    'deep',
    'degree',
    'delicate',
    'dependent',
    'design',
    'desire',
    'destruction',
    'detail',
    'development',
    'different',
    'digestion',
    'direction',
    'dirty',
    'discovery',
    'discussion',
    'disease',
    'disgust',
    'distance',
    'distribution',
    'division',
    'do',
    'dog',
    'door',
    'doubt',
    'down',
    'drain',
    'drawer',
    'dress',
    'drink',
    'driving',
    'drop',
    'dry',
    'dust',
    'ear',
    'early',
    'earth',
    'east',
    'edge',
    'education',
    'effect',
    'egg',
    'elastic',
    'electric',
    'end',
    'engine',
    'enough',
    'equal',
    'error',
    'even',
    'event',
    'ever',
    'every',
    'example',
    'exchange',
    'existence',
    'expansion',
    'experience',
    'expert',
    'eye',
    'face',
    'fact',
    'fall',
    'false',
    'family',
    'far',
    'farm',
    'fat',
    'father',
    'fear',
    'feather',
    'feeble',
    'feeling',
    'female',
    'fertile',
    'fiction',
    'field',
    'fight',
    'finger',
    'fire',
    'first',
    'fish',
    'fixed',
    'flag',
    'flame',
    'flat',
    'flight',
    'floor',
    'flower',
    'fly',
    'fold',
    'food',
    'foolish',
    'foot',
    'for',
    'force',
    'fork',
    'form',
    'forward',
    'fowl',
    'frame',
    'free',
    'frequent',
    'friend',
    'from',
    'front',
    'fruit',
    'full',
    'future',
    'garden',
    'general',
    'get',
    'girl',
    'give',
    'glass',
    'glove',
    'go',
    'goat',
    'gold',
    'good',
    'government',
    'grain',
    'grass',
    'great',
    'green',
    'grey',
    'grip',
    'group',
    'growth',
    'guide',
    'gun',
    'hair',
    'hammer',
    'hand',
    'hanging',
    'happy',
    'harbour',
    'hard',
    'harmony',
    'hat',
    'hate',
    'have',
    'he',
    'head',
    'healthy',
    'hear',
    'hearing',
    'heart',
    'heat',
    'help',
    'high',
    'history',
    'hole',
    'hollow',
    'hook',
    'hope',
    'horn',
    'horse',
    'hospital',
    'hour',
    'house',
    'how',
    'humour',
    'I',
    'ice',
    'idea',
    'if',
    'ill',
    'important',
    'impulse',
    'in',
    'increase',
    'industry',
    'ink',
    'insect',
    'instrument',
    'insurance',
    'interest',
    'invention',
    'iron',
    'island',
    'jelly',
    'jewel',
    'join',
    'journey',
    'judge',
    'jump',
    'keep',
    'kettle',
    'key',
    'kick',
    'kind',
    'kiss',
    'knee',
    'knife',
    'knot',
    'knowledge',
    'land',
    'language',
    'last',
    'late',
    'laugh',
    'law',
    'lead',
    'leaf',
    'learning',
    'leather',
    'left',
    'leg',
    'let',
    'letter',
    'level',
    'library',
    'lift',
    'light',
    'like',
    'limit',
    'line',
    'linen',
    'lip',
    'liquid',
    'list',
    'little',
    'living',
    'lock',
    'long',
    'look',
    'loose',
    'loss',
    'loud',
    'love',
    'low',
    'machine',
    'make',
    'male',
    'man',
    'manager',
    'map',
    'mark',
    'market',
    'married',
    'mass',
    'match',
    'material',
    'may',
    'meal',
    'measure',
    'meat',
    'medical',
    'meeting',
    'memory',
    'metal',
    'middle',
    'military',
    'milk',
    'mind',
    'mine',
    'minute',
    'mist',
    'mixed',
    'money',
    'monkey',
    'month',
    'moon',
    'morning',
    'mother',
    'motion',
    'mountain',
    'mouth',
    'move',
    'much',
    'muscle',
    'music',
    'nail',
    'name',
    'narrow',
    'nation',
    'natural',
    'near',
    'necessary',
    'neck',
    'need',
    'needle',
    'nerve',
    'net',
    'new',
    'news',
    'night',
    'no',
    'noise',
    'normal',
    'north',
    'nose',
    'not',
    'note',
    'now',
    'number',
    'nut',
    'observation',
    'of',
    'off',
    'offer',
    'office',
    'oil',
    'old',
    'on',
    'only',
    'open',
    'operation',
    'opinion',
    'opposite',
    'or',
    'orange',
    'order',
    'organization',
    'ornament',
    'other',
    'out',
    'oven',
    'over',
    'owner',
    'page',
    'pain',
    'paint',
    'paper',
    'parallel',
    'parcel',
    'part',
    'past',
    'paste',
    'payment',
    'peace',
    'pen',
    'pencil',
    'person',
    'physical',
    'picture',
    'pig',
    'pin',
    'pipe',
    'place',
    'plane',
    'plant',
    'plate',
    'play',
    'please',
    'pleasure',
    'plough',
    'pocket',
    'point',
    'poison',
    'polish',
    'political',
    'poor',
    'porter',
    'position',
    'possible',
    'pot',
    'potato',
    'powder',
    'power',
    'present',
    'price',
    'print',
    'prison',
    'private',
    'probable',
    'process',
    'produce',
    'profit',
    'property',
    'prose',
    'protest',
    'public',
    'pull',
    'pump',
    'punishment',
    'purpose',
    'push',
    'put',
    'quality',
    'question',
    'quick',
    'quiet',
    'quite',
    'rail',
    'rain',
    'range',
    'rat',
    'rate',
    'ray',
    'reaction',
    'reading',
    'ready',
    'reason',
    'receipt',
    'record',
    'red',
    'regret',
    'regular',
    'relation',
    'religion',
    'representative',
    'request',
    'respect',
    'responsible',
    'rest',
    'reward',
    'rhythm',
    'rice',
    'right',
    'ring',
    'river',
    'road',
    'rod',
    'roll',
    'roof',
    'room',
    'root',
    'rough',
    'round',
    'rub',
    'rule',
    'run',
    'sad',
    'safe',
    'sail',
    'salt',
    'same',
    'sand',
    'say',
    'scale',
    'school',
    'science',
    'scissors',
    'screw',
    'sea',
    'seat',
    'second',
    'secret',
    'secretary',
    'see',
    'seed',
    'seem',
    'selection',
    'self',
    'send',
    'sense',
    'separate',
    'serious',
    'servant',
    'sex',
    'shade',
    'shake',
    'shame',
    'sharp',
    'sheep',
    'shelf',
    'ship',
    'shirt',
    'shock',
    'shoe',
    'short',
    'shut',
    'side',
    'sign',
    'silk',
    'silver',
    'simple',
    'sister',
    'size',
    'skin',
    'skirt',
    'sky',
    'sleep',
    'slip',
    'slope',
    'slow',
    'small',
    'smash',
    'smell',
    'smile',
    'smoke',
    'smooth',
    'snake',
    'sneeze',
    'snow',
    'so',
    'soap',
    'society',
    'sock',
    'soft',
    'solid',
    'some',
    'son',
    'song',
    'sort',
    'sound',
    'soup',
    'south',
    'space',
    'spade',
    'special',
    'sponge',
    'spoon',
    'spring',
    'square',
    'stage',
    'stamp',
    'star',
    'start',
    'statement',
    'station',
    'steam',
    'steel',
    'stem',
    'step',
    'stick',
    'sticky',
    'stiff',
    'still',
    'stitch',
    'stocking',
    'stomach',
    'stone',
    'stop',
    'store',
    'story',
    'straight',
    'strange',
    'street',
    'stretch',
    'strong',
    'structure',
    'substance',
    'such',
    'sudden',
    'sugar',
    'suggestion',
    'summer',
    'sun',
    'support',
    'surprise',
    'sweet',
    'swim',
    'system',
    'table',
    'tail',
    'take',
    'talk',
    'tall',
    'taste',
    'tax',
    'teaching',
    'tendency',
    'test',
    'than',
    'that',
    'the',
    'then',
    'theory',
    'there',
    'thick',
    'thin',
    'thing',
    'this',
    'thought',
    'thread',
    'throat',
    'through',
    'through',
    'thumb',
    'thunder',
    'ticket',
    'tight',
    'till',
    'time',
    'tin',
    'tired',
    'to',
    'toe',
    'together',
    'tomorrow',
    'tongue',
    'tooth',
    'top',
    'touch',
    'town',
    'trade',
    'train',
    'transport',
    'tray',
    'tree',
    'trick',
    'trouble',
    'trousers',
    'true',
    'turn',
    'twist',
    'umbrella',
    'under',
    'unit',
    'up',
    'use',
    'value',
    'verse',
    'very',
    'vessel',
    'view',
    'violent',
    'voice',
    'waiting',
    'walk',
    'wall',
    'war',
    'warm',
    'wash',
    'waste',
    'watch',
    'water',
    'wave',
    'wax',
    'way',
    'weather',
    'week',
    'weight',
    'well',
    'west',
    'wet',
    'wheel',
    'when',
    'where',
    'while',
    'whip',
    'whistle',
    'white',
    'who',
    'why',
    'wide',
    'will',
    'wind',
    'window',
    'wine',
    'wing',
    'winter',
    'wire',
    'wise',
    'with',
    'woman',
    'wood',
    'wool',
    'word',
    'work',
    'worm',
    'wound',
    'writing',
    'wrong',
    'year',
    'yellow',
    'yes',
    'yesterday',
    'you',
    'young',
];


/* Generates password of set length with set qualities: 
numbers, words, special signs, big letters etc. */



var number_of_characters = 20;                                  // number of characters in password
var char_letters = 'abcdefghijklmnopqrstuvwxyz';                // ascii letters
var char_special = '!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~';        // ascii special characters
var char_numbers = '0123456789';                                // numbers

function charPool(small_letters, big_letters, special_signs, numbers) {        // function creates pool of characters to generate
    var pool = '';
    
    if (small_letters === true) {
        pool = pool + char_letters;
    } 
    
    if (big_letters === true) {
        pool = pool + char_letters.toUpperCase();
    } 
    
    if (special_signs === true) {
        pool = pool + char_special;
    }
    
    if (numbers === true){
        pool = pool + char_numbers;
    }
    return pool;
}

function randomChar(char_set) {
    var set = '';
    if (typeof char_set === "string") {                                                         // select random character from set
        set = char_set.charAt(Math.floor(Math.random() * char_set.length));
        return set;
    }   else if ( Array.isArray(char_set) ) {
        set = char_set[Math.floor(Math.random() * char_set.length)];
        return set;
    }   else {
        return('Wrong characters set: must be array or string');
    }
}

function capitalizeFirst(stringToModify, howMany) {
    var temp = stringToModify;
    var prefix_string = (temp.substr(0,howMany));
    prefix_string = prefix_string.toUpperCase();
    temp = temp.substr(howMany);
    temp = prefix_string + temp;
    return temp;
}   
// console.log(charPool(true, true, true));                                             // checking if character pool is correct

function totallyRandom(how_many_chars, pool) {           // generates string of specified length with selected additional signs
    var temp_string = '';
    for (var i = 0; i < how_many_chars; i++) {
        temp_string += randomChar(pool);                                                // randomChar chooses random character from character pool
    }
    return temp_string;
}

function addNumbers(stringToModify, howMany) {
    var suffix_string = totallyRandom(howMany, charPool(false,false,false,true));
    stringToModify = stringToModify + suffix_string;

    return stringToModify;
}


function bigLettersFirstThenRandomNumbersLast(password_length, prefix, suffix, pool) {          // need a better name - starts password with big letters, ends with numbers
    var temp_password = totallyRandom(password_length-suffix, pool);
 
    temp_password = capitalizeFirst(temp_password,prefix);
    temp_password = addNumbers(temp_password,suffix);
    
    return(temp_password);
}               

function mixed(number_of_characters) {                  //operations on arrays are easier
    var vowels = ['a','e','u','i','o'];                 
    var pool = charPool(true, false, false, false);
    var poolArray = [];
    var mixed_password = '';
    for (i=0; i<pool.length; i++) {                     //making pools of characters into arrat
        poolArray[i] = pool.charAt(i);
    }
    
    for (j=0; j<vowels.length; j++) {                       //deleting vowels from pool
        let index = poolArray.indexOf(vowels[j]);
        poolArray.splice(index,1);
    }
    
    for (k=0; k<number_of_characters; k++) {                //password is created from non-vovel and vowel one after another
        if (k%2===0) {
            mixed_password += randomChar(poolArray);

        } else {
            mixed_password += randomChar(vowels);
        }
    }
    
    return(mixed_password);
    }

function wordsPassword(number_of_characters) {
    var words_pass = '';
    
    while (words_pass.length != number_of_characters) {
        var rest = number_of_characters - words_pass.length;
        
        if (rest > 6) {
            var temp = randomChar(words);
            temp = capitalizeFirst(temp,1);
            words_pass += temp;

        } else {
            let random_word = randomChar(words);
            
            if (random_word.length == rest){
                random_word = capitalizeFirst(random_word,1);
                words_pass += random_word;
            } else {
                continue;
            }
        }
    }   
    return(words_pass);
}

//why working only one at a time??
totallyRandom_charPool = charPool(true,true,true,true);
anotherCharPool = charPool(true, false, false, false);
console.log(totallyRandom(number_of_characters, totallyRandom_charPool));                // check if totallyRandom works as expected
console.log(bigLettersFirstThenRandomNumbersLast(number_of_characters,3,3, anotherCharPool));             // check if works
console.log(mixed(number_of_characters));
console.log(wordsPassword(number_of_characters));




